services:
  - type: web
    name: clouddedupe
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: clouddedupe_master_2024_secret
      - key: PYTHON_VERSION
        value: 3.10.0